---
- hosts: all
  vars: 
    ansible_python_interpreter: /bin/python3
  become: yes
  become_user: root
  tasks: 
    - name: starte Datenbank
      docker_container: 
        image: mysql:latest
        name: mysql_db
        state: started
        ports:
          - "192.168.0.101:3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
        volumes: 
          - mysql:/var/lib/mysql

    - name: starte Wordpress
      docker_container:
        image: wordpress:latest
        name: wordpress_projekt
        state: started
        ports:
          - "192.168.0.99:80:80"
        env:
          WORDPRESS_DB_HOST: mysql_db
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: password
        links:
          - "mysql_db:mysql"
       # volumes: 
        #  - /var/lib/docker/volumes/wordpress_projekt:/var/www/html/wordpress
